apiVersion: batch/v1
kind: Job
metadata:
  name: stackhawk
  namespace: stackhawk
spec:
  template:
    spec:
      containers:
        - name: hawkscan
          image: stackhawk/hawkscan:latest
          imagePullPolicy: Always
          command:
            - shawk
            - stackhawk.d/stackhawk.yml
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: stackhawk-api-key
                  key: api-key
            - name: HAWK_GIT_REV
              value: main
            - name: HAWK_GIT_URL
              value: https://github.com/zconger/hawk-kube-job.git
      restartPolicy: Never
  backoffLimit: 4